### ISSUE TITLE
Auto-generate test jobs with a larger set of parameters

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/ci-jenkins-pipelines#58]
In [openjdk_build_pipeline.groovy/runTests](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L235), we [look for pre-created test job](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L269) names, run tests if we find them, and [print warning](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L285) if not.  This check could now be changed to check if job is not found, _generate_ it, then proceed to executing the test job.

Some options for approach are:

1. Grab the test job dsl file ([testJobTemplate](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate)) like how we [grab a single file from a separate repo in this getDependency](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/getDependency#L38) example and use it to generate jobs when they do not exist via the same approach as in Jenkinsfilebase (and how build jobs are generated)
1. Or run the [Test_Job_Auto_Gen](https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/) job to generate jobs, similar to the [OpenJ9 approach](https://github.com/eclipse/openj9/blob/a685bffd936bd787b3a6ec6cf247cfad571c9a5c/buildenv/jenkins/common/pipeline-functions.groovy#L610) 

The expected pattern is that at the time that a new JDK version is beginning to be built, a bunch of test jobs get created on that first attempt to run testing.  If we take option 1, it does not serve to refresh the test jobs, we do not regenerate each time we run them (which is perfectly fine, as we can trigger Test_Job_Auto_Gen directly for that purpose).  

We had previously kept this auto-gen of test jobs a manual process until now partly to understand what new test jobs were being requested.  Hopefully, by adding this auto-gen of test jobs will not further faciliate the lack of communication and awareness between build/test components, but still, now is a good time to introduce it.

This issue is related to other enhancements:
- expanding the set of test job parameters that can be set (needed by SmokeTestsFoBuildAndPackaging below to pass VENDOR_REPO/BRANCH and requested to add LABEL by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/issues/24)
- calling [SmokeTestsFoBuildAndPackaging](https://ci.adoptopenjdk.net/view/work-in-progress/job/SmokeTestsForBuildandPackaging/) from build pipelines (before any other tests are run, failure of this job should block all other testing) - see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2024
- updating testJobTemplate to generate a full set of test job parameters divided into logical groups with parameter separator - see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2238

**Comment by smlambert** [comment]
FYI @sophia-guo

**Comment by AdamBrousseau** [comment]
Just wanted to note that in the OpenJ9 scripts we generate both the build and test jobs every run in order to pickup any changes that went in or override if someone has manually hacked a job on the UI. Generally the time cost is minimal but we have run into issues with dsl taking several minutes to complete. I think it's usually faster if you run the dsl on master.

I do like the idea of not regenerating if the job exists. Perhaps it can be smart enough to check for a diff. I'm not sure if that's possible given you can change the outcome of dsl with passed in params.
