### ISSUE TITLE
Determine whether OpenJ9 builds still need the `mingw-cygwin` label

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/ci-jenkins-pipelines#66]
All of our machines should be configured the same so the [mingw-cygwin label](https://ci.adoptopenjdk.net/label/win2012&&mingw-cygwin&&build&&windows&&x64/) locks it onto the `ibmcloud` systems unnecessarily (in theory). We should verify whether the openj9 builds will run elsewhere (I think @Haroon-Khel has probably already verified the alibaba windows boxes)

**Comment by adamfarley** [comment]
Have asked Haroon to confirm about the [alibaba machine](https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-1/) on Slack.

Running builds on the azure machines now.

**Comment by Haroon-Khel** [comment]
As per @adamfarley's request, a fresh openj9 build on build-alibaba-win2012r2-x64-1
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/936/console

**Comment by sxa** [comment]
@Haroon-Khel Isn't that the same test you've alreayd done that worked at https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1818#issuecomment-785190334?

**Comment by Haroon-Khel** [comment]
> @Haroon-Khel Isn't that the same test you've already done that worked at AdoptOpenJDK/openjdk-infrastructure#1818 (comment)?

Yes, I mentioned that in the slack thread. Wouldnt hurt to run another one though; more recent

**Comment by adamfarley** [comment]
The only other two windows machines we could run on are the two azure machines. Here's a pair of jdk8 and jdk16 runs to check those:

build-azure-win2012r2-x64-1 (JDK16) - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16/job/jdk16-windows-x64-hotspot/57/
build-azure-win2012r2-x64-2 (JDK8) - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/1007/

**Comment by adamfarley** [comment]
Ok, results:

Azure machines: Builds and tests are green.
Alibaba machine: Build is green, handful of failures in the tests. Checking to make sure that there's nothing new.

**Comment by sxa** [comment]
>  Alibaba machine: Build is green, handful of failures in the tests. Checking to make sure that there's nothing new.

Presumably that was just with the build running on alibaba - the tests were still just running on whatever random machines they happened to land on?

**Comment by adamfarley** [comment]
Yes. The Alibaba build was tested on test-ibmcloud-win2012r2-x64-1.

**Comment by adamfarley** [comment]
Re-running the lang tests for the alibaba build on the machine that ran and passed the testing for the azure machines (which was, ironically, build-alibaba-win2012r2-x64-2).

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7366/console

**Comment by adamfarley** [comment]
Ok, those all passed. 

Looks to me like the sanity.openjdk tests *can* all pass on builds generated from the alibaba and azure machines, so the mingw label can be safely removed from the list of windows build requirements.

@Haroon-Khel - Your thoughts?
