### ISSUE TITLE
Update nightly and weekly test lists

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/ci-jenkins-pipelines#70]
As we have enabled testing for jdk16 and jdk17 and adding testing for some new platforms (see https://github.com/AdoptOpenJDK/openjdk-tests/pull/2304), revisit and adjust nightly and weekly test lists to suit the number of test jobs running on the set of test machines available.

Fix the case that sanity.external is being launched against some platforms that it should not be on (remove it from [here](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/build/common/build_base_file.groovy#L87)), and instead of subtracting it from corretto (in this [file](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L244)), add it for hotspot/openj9.

**Comment by sophia-guo** [comment]
Just to confirm that if external tests would be limited to hotspot and openj9 and disable all other impl, e.g, corretto, dragonwell, bisheng?

**Comment by smlambert** [comment]
Note that testing for alpine-linux has been added via #78 so this issue is really to address the `sanity.external` target that is in the default weekly list.  

@sophia-guo - I think for now, we should simply remove sanity.external from the list, and bring it back in once we have completed some issues in the openjdk-tests repo (to automatically update tag-versions and clean up the external tests a bit more).

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/issues/70#issuecomment-791539964 - when we bring these tests back in at a later time, we would limit to hotspot/openj9/dragonwell (and not run for corretto and bisheng is only on riscv, so would not apply for now either, based on its platform).
